from __future__ import annotations

import re
from dataclasses import dataclass

from ruleatlas_contracts.classification.scaffold_filter import is_non_business_rule_scaffold_line
from ruleatlas_contracts.enums import CommentClassification

DOMAIN_MODAL_SIGNALS = (
    "must not",
    "must",
    "cannot",
    "can't",
    "can only",
    "required",
    "forbidden",
    "allowed",
    "denied",
    "before",
    "after",
    "within",
    "expires",
    "expir",
    "retention",
    "retain",
    "admin",
    "user",
    "role",
    "permission",
    "status",
    "transition",
    "validate",
    "validation",
    "reject",
    "deny",
    "denied",
    "eligible",
    "ineligible",
    "assign",
    "assignment",
    "workflow",
    "billing",
    "payment",
    "pricing",
    "security",
    "unauthorized",
    "forbidden",
    "only ",
)

STRONG_DOMAIN_MODAL_SIGNALS = (
    "must not",
    "must",
    "cannot",
    "can't",
    "can only",
    "required",
    "forbidden",
    "denied",
    "not allowed",
    "only ",
    "shall not",
    "shall",
)

LICENSE_MARKERS = (
    "copyright",
    "all rights reserved",
    "permission is hereby granted",
    "mit license",
    "apache license",
    "gnu general public",
    "mozilla public license",
    "proprietary and confidential",
)

GENERATED_MARKERS = (
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "do not edit",
    "do not modify",
    "@generated",
    "code generated",
    "generated by",
)

TECHNICAL_MARKERS = (
    "helper",
    "utility",
    "internal use",
    "implementation detail",
    "workaround",
    "refactor",
    "performance",
    "optimization",
    "memoize",
    "cache",
    "wrapper",
    "plumbing",
    "boilerplate",
    "styling",
    "stylesheet",
    "import ",
    "setup",
    "configure",
    "initializ",
    "renders",
    "component props",
    "callback",
    "typescript",
    "eslint",
    "fastapi",
    "dependencies",
    "typed alias",
    "annotated",
    "depends(",
)

TECHNICAL_HEADER_PHRASES = (
    "helpers for routes",
    "pydantic bodies for routes",
    "admin-specific http error bodies",
    "admin lessons (native",
    "route helpers",
    "dependency injection helper",
    "internal helpers",
    "shared helpers",
    "http error bodies",
    "response bodies",
    "composed fastapi",
    "fastapi dependencies",
    "typed aliases",
    "use these typed",
    "instead of repeating",
    "repository kit",
    "production code must use",
    "must use phobos",
)

PARAM_DOC_MARKERS = (
    ":param",
    "@param",
    "args:",
    "arguments:",
    "parameters:",
    "returns:",
    ":return",
    ":rtype",
    "raises:",
    "@returns",
    "@type",
)

SCAFFOLD_COMMENT_MARKERS = (
    "vitest",
    "jest",
    "mock",
    "test scaffold",
    "testing-library",
    "snapshot",
    "eslint-disable",
)

TRIPLE_QUOTE_DELIMITERS = ('"""', "'''")
BLOCK_COMMENT_DELIMITERS = ("/*", "*/")
PYTHON_LINE_COMMENT = re.compile(r"^\s*#(.*)$")
JS_LINE_COMMENT = re.compile(r"^\s*//(.*)$")
INLINE_PYTHON_COMMENT = re.compile(r"\s#([^#].*)$")
INLINE_JS_COMMENT = re.compile(r"\s//([^/].*)$")
TODO_PATTERN = re.compile(r"\b(todo|fixme|hack|xxx)\b", re.IGNORECASE)
BULLET_RULE_PATTERN = re.compile(r"^\s*[-*]\s+(\S.*)$", re.MULTILINE)


@dataclass(frozen=True)
class CommentBlock:
    start_line: int
    end_line: int
    content: str
    is_docstring: bool


def _find_delimited_ranges(
    text: str,
    *,
    opening_delimiters: tuple[str, ...],
    closing_delimiter: str | None = None,
) -> list[tuple[int, int]]:
    """Find non-overlapping delimited ranges without unbounded regex backtracking."""
    ranges: list[tuple[int, int]] = []
    position = 0
    while position < len(text):
        openings = [(text.find(delimiter, position), delimiter) for delimiter in opening_delimiters]
        start, opening = min(
            (candidate for candidate in openings if candidate[0] >= 0),
            default=(-1, ""),
            key=lambda candidate: candidate[0],
        )
        if start < 0:
            break
        closing = closing_delimiter or opening
        end = text.find(closing, start + len(opening))
        if end < 0:
            position = start + len(opening)
            continue
        ranges.append((start, end + len(closing)))
        position = end + len(closing)
    return ranges


def _append_delimited_blocks(
    text: str,
    ranges: list[tuple[int, int]],
    *,
    is_docstring: bool,
    blocks: list[CommentBlock],
    consumed_ranges: list[tuple[int, int]],
    skip_overlaps: bool = False,
) -> None:
    for start, end in ranges:
        if skip_overlaps and _range_overlaps(start, end, consumed_ranges):
            continue
        content = _strip_comment_markers(text[start:end])
        if content.strip():
            blocks.append(
                CommentBlock(
                    start_line=text.count("\n", 0, start) + 1,
                    end_line=text.count("\n", 0, end) + 1,
                    content=content,
                    is_docstring=is_docstring,
                )
            )
        consumed_ranges.append((start, end))


def _line_comment_body(line: str) -> str | None:
    python_match = PYTHON_LINE_COMMENT.match(line)
    if python_match:
        return python_match.group(1)
    js_match = JS_LINE_COMMENT.match(line)
    if js_match:
        return js_match.group(1)
    return None


def _collect_consecutive_line_comments(lines: list[str], start_index: int) -> tuple[list[str], int, int]:
    first = _line_comment_body(lines[start_index])
    assert first is not None
    comment_lines = [first]
    end = start_index + 1
    next_index = start_index + 1
    while next_index < len(lines):
        body = _line_comment_body(lines[next_index])
        if body is None:
            break
        comment_lines.append(body)
        end = next_index + 1
        next_index += 1
    return comment_lines, end, next_index


def _inline_comment_content(line: str) -> str | None:
    inline_python = INLINE_PYTHON_COMMENT.search(line)
    if inline_python and not line.strip().startswith("#"):
        return inline_python.group(1).strip()
    inline_js = INLINE_JS_COMMENT.search(line)
    if inline_js and not line.strip().startswith("//"):
        code_part = line.split("//", 1)[0]
        if "://" not in code_part:
            return inline_js.group(1).strip()
    return None


def _extract_line_comment_blocks(
    text: str,
    lines: list[str],
    consumed_ranges: list[tuple[int, int]],
) -> list[CommentBlock]:
    blocks: list[CommentBlock] = []
    line_index = 0
    while line_index < len(lines):
        line_no = line_index + 1
        if _line_in_consumed_range(line_no, text, consumed_ranges):
            line_index += 1
            continue
        if _line_comment_body(lines[line_index]) is not None:
            comment_lines, end, next_index = _collect_consecutive_line_comments(lines, line_index)
            content = "\n".join(part.strip() for part in comment_lines if part.strip())
            if content:
                blocks.append(
                    CommentBlock(start_line=line_no, end_line=end, content=content, is_docstring=False)
                )
            line_index = next_index
            continue
        inline_content = _inline_comment_content(lines[line_index])
        if inline_content:
            blocks.append(
                CommentBlock(
                    start_line=line_no,
                    end_line=line_no,
                    content=inline_content,
                    is_docstring=False,
                )
            )
        line_index += 1
    return blocks


def extract_comment_blocks(text: str) -> list[CommentBlock]:
    blocks: list[CommentBlock] = []
    consumed_ranges: list[tuple[int, int]] = []
    _append_delimited_blocks(
        text,
        _find_delimited_ranges(text, opening_delimiters=TRIPLE_QUOTE_DELIMITERS),
        is_docstring=True,
        blocks=blocks,
        consumed_ranges=consumed_ranges,
    )
    _append_delimited_blocks(
        text,
        _find_delimited_ranges(
            text,
            opening_delimiters=(BLOCK_COMMENT_DELIMITERS[0],),
            closing_delimiter=BLOCK_COMMENT_DELIMITERS[1],
        ),
        is_docstring=False,
        blocks=blocks,
        consumed_ranges=consumed_ranges,
        skip_overlaps=True,
    )
    blocks.extend(_extract_line_comment_blocks(text, text.splitlines(), consumed_ranges))
    return blocks


def _is_scaffold_comment(content: str, lowered: str) -> bool:
    if any(marker in lowered for marker in SCAFFOLD_COMMENT_MARKERS):
        return True
    return any(
        is_non_business_rule_scaffold_line(f"// {line}") for line in content.splitlines() if line.strip()
    )


def _classify_docstring(content: str, has_domain: bool) -> CommentClassification:
    if _is_param_only_docstring(content):
        return CommentClassification.DOCSTRING_TECHNICAL
    if has_domain:
        return CommentClassification.DOCSTRING_DOMAIN_BEHAVIOR
    return CommentClassification.DOCSTRING_TECHNICAL


def _classify_domain_or_technical(content: str, lowered: str, has_domain: bool) -> CommentClassification:
    if has_domain:
        if any(marker in lowered for marker in TECHNICAL_MARKERS) and not _has_strong_domain_modal_signal(content):
            return CommentClassification.TECHNICAL_COMMENT
        return CommentClassification.DOMAIN_BEHAVIOR_COMMENT
    return CommentClassification.TECHNICAL_COMMENT


def classify_comment_block(block: CommentBlock) -> CommentClassification:
    content = block.content.strip()
    lowered = content.lower()
    if not content:
        return CommentClassification.TECHNICAL_COMMENT
    if any(marker in lowered for marker in LICENSE_MARKERS):
        return CommentClassification.LICENSE_HEADER
    if any(marker in lowered for marker in GENERATED_MARKERS):
        return CommentClassification.GENERATED_FILE_COMMENT
    if _is_scaffold_comment(content, lowered):
        return CommentClassification.SCAFFOLD_COMMENT
    if any(phrase in lowered for phrase in TECHNICAL_HEADER_PHRASES):
        return CommentClassification.TECHNICAL_COMMENT

    has_todo = bool(TODO_PATTERN.search(content))
    has_domain = _has_domain_behavior_signal(content)
    if has_todo and not has_domain:
        return CommentClassification.TODO_COMMENT
    if block.is_docstring:
        return _classify_docstring(content, has_domain)
    if has_todo and has_domain:
        return CommentClassification.DOMAIN_BEHAVIOR_COMMENT
    return _classify_domain_or_technical(content, lowered, has_domain)


def is_extractable_domain_comment(classification: CommentClassification) -> bool:
    return classification in {
        CommentClassification.DOMAIN_BEHAVIOR_COMMENT,
        CommentClassification.DOCSTRING_DOMAIN_BEHAVIOR,
    }


def split_independent_domain_rules(content: str) -> list[str]:
    normalized = _normalize_comment_content(content)
    if not normalized:
        return []

    bullets = BULLET_RULE_PATTERN.findall(normalized)
    domain_bullets = [bullet.strip() for bullet in bullets if _has_domain_behavior_signal(bullet)]
    if len(domain_bullets) > 1:
        return domain_bullets

    paragraphs = [part.strip() for part in re.split(r"\n\s*\n", normalized) if part.strip()]
    domain_paragraphs = [part for part in paragraphs if _has_domain_behavior_signal(part)]
    if len(domain_paragraphs) > 1:
        return domain_paragraphs

    return [normalized]


def find_domain_comment_candidates(text: str) -> list[tuple[CommentBlock, str, CommentClassification]]:
    results: list[tuple[CommentBlock, str, CommentClassification]] = []
    for block in extract_comment_blocks(text):
        classification = classify_comment_block(block)
        if not is_extractable_domain_comment(classification):
            continue
        for claim in split_independent_domain_rules(block.content):
            if _has_domain_behavior_signal(claim):
                results.append((block, claim, classification))
    return results


def code_text_without_comments(text: str) -> str:
    comment_ranges = _find_delimited_ranges(text, opening_delimiters=TRIPLE_QUOTE_DELIMITERS)
    comment_ranges.extend(
        _find_delimited_ranges(
            text,
            opening_delimiters=(BLOCK_COMMENT_DELIMITERS[0],),
            closing_delimiter=BLOCK_COMMENT_DELIMITERS[1],
        )
    )
    cleaned_characters = list(text)
    for start, end in comment_ranges:
        cleaned_characters[start:end] = " " * (end - start)
    cleaned = "".join(cleaned_characters)

    output_lines: list[str] = []
    for line in cleaned.splitlines():
        stripped = line
        if re.match(r"^\s*#", stripped):
            output_lines.append("")
            continue
        if re.match(r"^\s*//", stripped):
            output_lines.append("")
            continue
        stripped = INLINE_PYTHON_COMMENT.sub("", stripped)
        if "//" in stripped:
            code_part, _, _comment_part = stripped.partition("//")
            if "://" not in code_part:
                stripped = code_part
        output_lines.append(stripped)
    return "\n".join(output_lines)


def _has_domain_behavior_signal(text: str) -> bool:
    lowered = text.lower()
    for signal in DOMAIN_MODAL_SIGNALS:
        token = signal.strip()
        if len(token) <= 5:
            if re.search(rf"\b{re.escape(token)}\b", lowered):
                return True
        elif signal in lowered:
            return True
    return False


def _has_strong_domain_modal_signal(text: str) -> bool:
    lowered = text.lower()
    return any(signal in lowered for signal in STRONG_DOMAIN_MODAL_SIGNALS)


def _is_param_only_docstring(content: str) -> bool:
    lowered = content.lower()
    has_param_docs = any(marker in lowered for marker in PARAM_DOC_MARKERS)
    if not has_param_docs:
        return False
    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        line_lower = stripped.lower()
        if any(marker in line_lower for marker in PARAM_DOC_MARKERS):
            continue
        if re.match(r"^[a-z_][\w]*:\s", line_lower):
            continue
        if _has_domain_behavior_signal(stripped):
            return False
    return True


def _normalize_comment_content(content: str) -> str:
    lines = []
    for line in content.splitlines():
        stripped = line.strip()
        stripped = stripped.lstrip("*").strip()
        if stripped:
            lines.append(stripped)
    return "\n".join(lines).strip()


def _strip_comment_markers(raw: str) -> str:
    text = raw.strip()
    if text.startswith(('"""', "'''")):
        return text[3:-3].strip()
    if text.startswith("/*"):
        return text[2:-2].strip()
    return text.lstrip("#/").strip()


def _range_overlaps(start: int, end: int, ranges: list[tuple[int, int]]) -> bool:
    return any(not (end <= existing_start or start >= existing_end) for existing_start, existing_end in ranges)


def _line_in_consumed_range(line_no: int, text: str, ranges: list[tuple[int, int]]) -> bool:
    line_start = sum(len(line) + 1 for line in text.splitlines(True)[: line_no - 1])
    line_end = line_start + len(text.splitlines()[line_no - 1])
    return _range_overlaps(line_start, line_end, ranges)
