"""Built-in global file type mappings for discovery."""

from __future__ import annotations

from ruleatlas_discovery.constants import (
    NO_EXTENSION,
    UNKNOWN_LANGUAGE_KEY,
    BucketHint,
    CommentStyle,
    FileKind,
    MatchType,
)
from ruleatlas_discovery.models import FileTypeMapping


def _ext(
    suffix: str,
    *,
    language: str,
    language_key: str,
    display_type: str | None = None,
    file_kind: FileKind = FileKind.CODE,
    bucket: BucketHint = BucketHint.PRODUCTION,
    comment_style: CommentStyle = CommentStyle.SLASH,
    is_binary: bool = False,
    is_generated_hint: bool = False,
    description: str = "",
) -> FileTypeMapping:
    normalized = suffix if suffix.startswith(".") else f".{suffix}"
    return FileTypeMapping(
        pattern=normalized.lower(),
        match_type=MatchType.EXTENSION,
        language=language,
        language_key=language_key,
        display_type=display_type or normalized,
        file_kind=file_kind,
        default_bucket_hint=bucket,
        comment_style=comment_style,
        is_binary=is_binary,
        is_generated_hint=is_generated_hint,
        description=description,
    )


def _filename(
    name: str,
    *,
    language: str,
    language_key: str,
    display_type: str,
    file_kind: FileKind,
    bucket: BucketHint,
    comment_style: CommentStyle,
    is_generated_hint: bool = False,
    description: str = "",
) -> FileTypeMapping:
    return FileTypeMapping(
        pattern=name,
        match_type=MatchType.FILENAME,
        language=language,
        language_key=language_key,
        display_type=display_type,
        file_kind=file_kind,
        default_bucket_hint=bucket,
        comment_style=comment_style,
        is_generated_hint=is_generated_hint,
        description=description,
    )


def _glob(
    pattern: str,
    *,
    language: str,
    language_key: str,
    display_type: str,
    file_kind: FileKind,
    bucket: BucketHint,
    comment_style: CommentStyle,
    normalized_extension: str | None = None,
    description: str = "",
) -> FileTypeMapping:
    return FileTypeMapping(
        pattern=pattern,
        match_type=MatchType.GLOB,
        language=language,
        language_key=language_key,
        display_type=display_type,
        file_kind=file_kind,
        default_bucket_hint=bucket,
        comment_style=comment_style,
        normalized_extension=normalized_extension,
        description=description,
    )


def built_in_file_type_mappings() -> list[FileTypeMapping]:
    entries: list[FileTypeMapping] = [
        # Filename matches (highest precedence)
        _filename(
            "package.json",
            language="JSON",
            language_key="json",
            display_type="npm package manifest",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _filename(
            "CMakeLists.txt",
            language="CMake",
            language_key="cmake",
            display_type="CMake build script",
            file_kind=FileKind.BUILD,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _filename(
            "coverage.xml",
            language="Coverage",
            language_key="xml",
            display_type="Coverage report (XML)",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.HTML,
            is_generated_hint=True,
        ),
        _filename(
            "junit.xml",
            language="Test report",
            language_key="xml",
            display_type="JUnit test report",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.HTML,
            is_generated_hint=True,
        ),
        _filename(
            "NOTICE",
            language="Notice",
            language_key="text",
            display_type="Notice file",
            file_kind=FileKind.DOCUMENTATION,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.NONE,
        ),
        _filename(
            "README",
            language="Text",
            language_key="text",
            display_type="Readme",
            file_kind=FileKind.DOCUMENTATION,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.NONE,
        ),
        _filename(
            "Procfile",
            language="Procfile",
            language_key="config",
            display_type="Process manifest",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _filename(
            "Jenkinsfile",
            language="Jenkins",
            language_key="groovy",
            display_type="Jenkins pipeline",
            file_kind=FileKind.BUILD,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.SLASH,
        ),
        _filename(
            "Vagrantfile",
            language="Vagrant",
            language_key="ruby",
            display_type="Vagrant config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _filename(
            "CODEOWNERS",
            language="Code owners",
            language_key="config",
            display_type="Code owners",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _filename(
            ".gitignore",
            language="Git ignore",
            language_key="config",
            display_type="Git ignore",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _filename(
            ".dockerignore",
            language="Docker ignore",
            language_key="config",
            display_type="Docker ignore",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _filename(
            ".editorconfig",
            language="EditorConfig",
            language_key="config",
            display_type="Editor config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _filename(
            ".npmrc",
            language="npm config",
            language_key="config",
            display_type="npm config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _filename(
            ".nvmrc",
            language="Node version",
            language_key="config",
            display_type="Node version",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _filename(
            ".python-version",
            language="Python version",
            language_key="config",
            display_type="Python version",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _filename(
            ".prettierignore",
            language="Prettier ignore",
            language_key="config",
            display_type="Prettier ignore",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _filename(
            "py.typed",
            language="Python typing marker",
            language_key="python",
            display_type="Python typing marker",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
            description="PEP 561 typing marker file",
        ),
        _filename(
            ".eslintignore",
            language="ESLint ignore",
            language_key="config",
            display_type="ESLint ignore",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _filename(
            "vite.config.ts",
            language="Vite",
            language_key="typescript",
            display_type="Vite config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.SLASH,
            description="Vite bundler configuration (TypeScript)",
        ),
        _filename(
            "eslint.config.ts",
            language="ESLint",
            language_key="typescript",
            display_type="ESLint config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.SLASH,
            description="ESLint flat configuration (TypeScript)",
        ),
        _filename(
            "sonar-project.properties",
            language="Sonar",
            language_key="properties",
            display_type="Sonar project properties",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
            description="SonarQube project configuration",
        ),
        # Glob hints
        _glob(
            "*docker-compose*.y*ml",
            language="Docker Compose",
            language_key="yaml",
            display_type="Docker Compose",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.YAML,
            normalized_extension=".yaml",
            description="Docker Compose (.yml/.yaml, including overrides)",
        ),
        _glob(
            "*.y*ml",
            language="YAML",
            language_key="yaml",
            display_type="YAML",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.YAML,
            normalized_extension=".yaml",
            description="YAML config (.yml and .yaml)",
        ),
        _glob(
            "*[Ll][Ii][Cc][Ee][Nn][CS][Ee]",
            language="License",
            language_key="text",
            display_type="License",
            file_kind=FileKind.DOCUMENTATION,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.NONE,
            description="LICENSE / LICENCE (any path, case-insensitive basename)",
        ),
        _glob(
            "*Makefile",
            language="Makefile",
            language_key="makefile",
            display_type="Makefile",
            file_kind=FileKind.BUILD,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
            description="Makefile and GNUMakefile",
        ),
        _glob(
            "*.spec.ts",
            language="TypeScript",
            language_key="typescript",
            display_type="TypeScript spec test",
            file_kind=FileKind.TEST,
            bucket=BucketHint.TESTS,
            comment_style=CommentStyle.SLASH,
        ),
        _glob(
            "*.test.ts",
            language="TypeScript",
            language_key="typescript",
            display_type="TypeScript unit test",
            file_kind=FileKind.TEST,
            bucket=BucketHint.TESTS,
            comment_style=CommentStyle.SLASH,
        ),
        _glob(
            "*.test.tsx",
            language="TSX",
            language_key="tsx",
            display_type="React test",
            file_kind=FileKind.TEST,
            bucket=BucketHint.TESTS,
            comment_style=CommentStyle.SLASH,
            description="React component tests (*.test.tsx)",
        ),
        _glob(
            ".env*(.*)",
            language="Environment",
            language_key="env",
            display_type="Environment variables",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
            normalized_extension=NO_EXTENSION,
            description="Environment variables (.env, .env.test, .env.dist, etc.)",
        ),
        _glob(
            "Dockerfile*(.*)",
            language="Dockerfile",
            language_key="dockerfile",
            display_type="Dockerfile",
            file_kind=FileKind.BUILD,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
            normalized_extension=NO_EXTENSION,
            description="Dockerfile and variants (Dockerfile.dev, Dockerfile.prod, etc.)",
        ),
        _glob(
            "tsconfig*(.*).json",
            language="TypeScript",
            language_key="typescript",
            display_type="TypeScript config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
            description="TypeScript compiler config (tsconfig.json, tsconfig.node.json, etc.)",
        ),
        _glob(
            "test_*.py",
            language="Python",
            language_key="python",
            display_type="Python test",
            file_kind=FileKind.TEST,
            bucket=BucketHint.TESTS,
            comment_style=CommentStyle.HASH,
            description="Python files named test_*.py",
        ),
        _glob(
            "**/generated/**",
            language="Generated",
            language_key=UNKNOWN_LANGUAGE_KEY,
            display_type="Generated output",
            file_kind=FileKind.GENERATED,
            bucket=BucketHint.GENERATED_VENDOR,
            comment_style=CommentStyle.UNSUPPORTED,
            description="Generated output paths",
        ),
        # Code — C-style comments
        _ext(
            ".py",
            language="Python",
            language_key="python",
            display_type="Python source",
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".pyc",
            language="Python bytecode",
            language_key="python",
            display_type="Compiled bytecode",
            file_kind=FileKind.GENERATED,
            bucket=BucketHint.GENERATED_VENDOR,
            comment_style=CommentStyle.NONE,
            is_binary=True,
            is_generated_hint=True,
            description="Compiled Python bytecode",
        ),
        _ext(
            ".pyo",
            language="Python bytecode",
            language_key="python",
            display_type="Optimized bytecode",
            file_kind=FileKind.GENERATED,
            bucket=BucketHint.GENERATED_VENDOR,
            comment_style=CommentStyle.NONE,
            is_binary=True,
            is_generated_hint=True,
            description="Optimized Python bytecode (legacy)",
        ),
        _ext(
            ".pyd",
            language="Python extension",
            language_key="python",
            display_type="Python extension module",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
            is_binary=True,
            is_generated_hint=True,
            description="Python native extension module (Windows)",
        ),
        _ext(
            ".pyi",
            language="Python stub",
            language_key="python",
            display_type="Type stub",
            file_kind=FileKind.CODE,
            bucket=BucketHint.PRODUCTION,
            comment_style=CommentStyle.HASH,
            description="PEP 484 stub file",
        ),
        _ext(
            ".mako",
            language="Mako",
            language_key="python",
            display_type="Mako template",
            file_kind=FileKind.CODE,
            bucket=BucketHint.PRODUCTION,
            comment_style=CommentStyle.HASH,
            description="Mako template",
        ),
        _ext(".js", language="JavaScript", language_key="javascript", display_type="JavaScript source"),
        _ext(".jsx", language="JSX", language_key="jsx", display_type="React JSX"),
        _ext(".ts", language="TypeScript", language_key="typescript", display_type="TypeScript source"),
        _ext(".tsx", language="TSX", language_key="tsx", display_type="React TSX"),
        _ext(".mjs", language="JavaScript", language_key="javascript", display_type="ES module"),
        _ext(".cjs", language="JavaScript", language_key="javascript", display_type="CommonJS module"),
        _ext(".java", language="Java", language_key="java", display_type="Java source"),
        _ext(".cs", language="C#", language_key="csharp", display_type="C# source"),
        _ext(".go", language="Go", language_key="go", display_type="Go source"),
        _ext(".rb", language="Ruby", language_key="ruby", display_type="Ruby source", comment_style=CommentStyle.HASH),
        _ext(".php", language="PHP", language_key="php", display_type="PHP source"),
        _ext(".rs", language="Rust", language_key="rust", display_type="Rust source"),
        _ext(".kt", language="Kotlin", language_key="kotlin", display_type="Kotlin source"),
        _ext(".swift", language="Swift", language_key="swift", display_type="Swift source"),
        _ext(".scala", language="Scala", language_key="scala", display_type="Scala source"),
        _ext(".sql", language="SQL", language_key="sql", display_type="SQL script", comment_style=CommentStyle.SQL),
        # Docs / domain
        _ext(
            ".md",
            language="Markdown",
            language_key="markdown",
            display_type="Markdown document",
            file_kind=FileKind.DOCUMENTATION,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.HTML,
        ),
        _ext(
            ".mdx",
            language="MDX",
            language_key="markdown",
            display_type="MDX document",
            file_kind=FileKind.DOCUMENTATION,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.HTML,
        ),
        _ext(
            ".mdc",
            language="Markdown",
            language_key="markdown",
            display_type="Cursor rule (Markdown)",
            file_kind=FileKind.DOCUMENTATION,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.HTML,
            description="Markdown component / Cursor rules",
        ),
        _ext(
            ".rst",
            language="reStructuredText",
            language_key="rst",
            display_type="reStructuredText document",
            file_kind=FileKind.DOCUMENTATION,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".txt",
            language="Text",
            language_key="text",
            display_type="Plain text",
            file_kind=FileKind.DOCUMENTATION,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".feature",
            language="Gherkin",
            language_key="gherkin",
            display_type="Gherkin feature",
            file_kind=FileKind.TEST,
            bucket=BucketHint.TESTS,
            comment_style=CommentStyle.HASH,
        ),
        # Config / data
        _ext(
            ".json",
            language="JSON",
            language_key="json",
            display_type="JSON data",
            file_kind=FileKind.DATA,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".toml",
            language="TOML",
            language_key="toml",
            display_type="TOML config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".ini",
            language="INI",
            language_key="ini",
            display_type="INI config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".conf",
            language="Config",
            language_key="config",
            display_type="Config file",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".cfg",
            language="Config",
            language_key="config",
            display_type="Config settings",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".properties",
            language="Properties",
            language_key="properties",
            display_type="Java properties",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".localstack",
            language="LocalStack",
            language_key="config",
            display_type="LocalStack config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".production",
            language="Production config",
            language_key="config",
            display_type="Production config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".ebcli",
            language="Elastic Beanstalk CLI",
            language_key="config",
            display_type="Elastic Beanstalk config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".typed",
            language="Python typing marker",
            language_key="python",
            display_type="Typing marker",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
            description="PEP 561 typing marker file",
        ),
        # Web / assets
        _ext(
            ".html",
            language="HTML",
            language_key="html",
            display_type="HTML page",
            file_kind=FileKind.CODE,
            bucket=BucketHint.PRODUCTION,
            comment_style=CommentStyle.HTML,
        ),
        _ext(
            ".css",
            language="CSS",
            language_key="css",
            display_type="CSS stylesheet",
            comment_style=CommentStyle.SLASH,
        ),
        _ext(
            ".scss",
            language="SCSS",
            language_key="scss",
            display_type="SCSS stylesheet",
            comment_style=CommentStyle.SLASH,
        ),
        _ext(
            ".sass",
            language="Sass",
            language_key="sass",
            display_type="Sass stylesheet",
            comment_style=CommentStyle.SLASH,
        ),
        _ext(
            ".less",
            language="Less",
            language_key="less",
            display_type="Less stylesheet",
            comment_style=CommentStyle.SLASH,
        ),
        _ext(
            ".svg",
            language="SVG",
            language_key="xml",
            display_type="SVG image",
            file_kind=FileKind.DATA,
            bucket=BucketHint.DOCS,
            comment_style=CommentStyle.HTML,
        ),
        _ext(
            ".xml",
            language="XML",
            language_key="xml",
            display_type="XML data",
            file_kind=FileKind.DATA,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HTML,
        ),
        # Scripts / build
        _ext(
            ".sh",
            language="Shell",
            language_key="shell",
            display_type="Shell script",
            file_kind=FileKind.SCRIPT,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".bash",
            language="Shell",
            language_key="shell",
            display_type="Bash script",
            file_kind=FileKind.SCRIPT,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".zsh",
            language="Shell",
            language_key="shell",
            display_type="Zsh script",
            file_kind=FileKind.SCRIPT,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".ps1",
            language="PowerShell",
            language_key="powershell",
            display_type="PowerShell script",
            file_kind=FileKind.SCRIPT,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".bat",
            language="Batch",
            language_key="batch",
            display_type="Batch script",
            file_kind=FileKind.SCRIPT,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".cmd",
            language="Batch",
            language_key="batch",
            display_type="Command script",
            file_kind=FileKind.SCRIPT,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".mk",
            language="Make",
            language_key="makefile",
            display_type="Makefile fragment",
            file_kind=FileKind.BUILD,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        # Artifacts / logs
        _ext(
            ".map",
            language="Source map",
            language_key="json",
            display_type="Source map",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
            is_generated_hint=True,
            description="JavaScript/CSS source map",
        ),
        _ext(
            ".sample",
            language="Example/config",
            language_key="config",
            display_type="Sample config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
            description="Sample/template config (e.g. env.sample)",
        ),
        _ext(
            ".log",
            language="Log",
            language_key="log",
            display_type="Log file",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".out",
            language="Output",
            language_key="log",
            display_type="Output file",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".output",
            language="Output",
            language_key="log",
            display_type="Output log",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".test",
            language="Test",
            language_key=UNKNOWN_LANGUAGE_KEY,
            display_type="Test artifact",
            file_kind=FileKind.TEST,
            bucket=BucketHint.TESTS,
            comment_style=CommentStyle.UNSUPPORTED,
            description="Generic test artifact extension",
        ),
        _ext(
            ".phobos-api",
            language="Phobos API",
            language_key="config",
            display_type="Phobos API descriptor",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
            description="DeliveryPlus Phobos API descriptor",
        ),
        _ext(
            ".in",
            language="Config",
            language_key="config",
            display_type="Template input",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
            description="Setuptools/manifest template (e.g. MANIFEST.in)",
        ),
        _ext(
            ".pyl",
            language="Pylint config",
            language_key="config",
            display_type="Pylint config",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.HASH,
        ),
        _ext(
            ".lock",
            language="Lockfile",
            language_key="config",
            display_type="Lock file",
            file_kind=FileKind.CONFIG,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
            is_generated_hint=True,
        ),
        _ext(
            ".csv",
            language="CSV",
            language_key="csv",
            display_type="CSV data",
            file_kind=FileKind.DATA,
            bucket=BucketHint.CONFIG,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".coverage",
            language="Coverage",
            language_key="coverage",
            display_type="Coverage data",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
            is_generated_hint=True,
        ),
        _ext(
            ".whl",
            language="Python wheel",
            language_key=UNKNOWN_LANGUAGE_KEY,
            display_type="Python wheel",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
            is_binary=True,
        ),
        _ext(
            ".dist",
            language="Distribution artifact",
            language_key=UNKNOWN_LANGUAGE_KEY,
            display_type="Distribution artifact",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
        ),
        _ext(
            ".node",
            language="Node artifact",
            language_key=UNKNOWN_LANGUAGE_KEY,
            display_type="Node native addon",
            file_kind=FileKind.ARTIFACT,
            bucket=BucketHint.ARTIFACTS,
            comment_style=CommentStyle.NONE,
            is_binary=True,
        ),
    ]
    return entries
